---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:amd64-7.4.162
    container_name: unifi-controller 
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Honolulu
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /opt/unifi-controller/config:/config
    ports:
      - 192.168.55.3:8443:8443
      - 192.168.55.3:3478:3478/udp
      - 192.168.55.3:10001:10001/udp
      - 192.168.55.3:8080:8080 
      - 1900:1900/udp #optional 
      - 8843:8843 #optional
      - 8880:8880 #optional 
      - 6789:6789 #optional
      - 5514:5514/udp #optional 
    restart: unless-stopped 
