---
version: "3"

services:
  bind9:
    container_name: dns-prd-01
    image: ubuntu/bind9:9.16-20.04_beta
    environment:
      - BIND9_USER=root
      - TZ=Pacific/Honolulu
    ports:
      - "192.168.55.3:53:53/tcp"
      - "192.168.55.3:53:53/udp"
    volumes:
      - ./config:/etc/bind 
      - ./cache:/var/cache/bind 
      - ./records:/var/lib/bind 
    restart: unless-stopped
